In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plotly
import seaborn as sns
import plotly.express as px

In [16]:
import tensorflow as tf

In [18]:
from tensorflow.keras.models import Sequential

In [19]:
from tensorflow.keras.models import load_model

In [26]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [20]:
final_model = load_model('final_model.h5')
final_model

In [22]:
df = pd.read_csv('Clean_dash.csv').drop('Unnamed: 0', axis=1)
df

Age  History  Tremor  Leg agility  Entropy of speech timing (-)  \
0     72.0        0       1            0                      1.564000   
1     72.0        0       1            0                      1.564000   
2     72.0        0       1            0                      1.550000   
3     72.0        0       1            0                      1.519000   
4     72.0        0       1            0                      1.543000   
...    ...      ...     ...          ...                           ...   
3313  60.0        0       0            0                      2.574964   
3314  60.0        0       0            0                      2.575286   
3315  60.0        0       0            0                      2.575607   
3316  60.0        0       0            0                      2.575929   
3317  60.0        0       0            0                      2.576250   

      Acceleration of speech timing(-/min2)  Duration of pause intervals (ms)  \
0                                  6.050000                         146.00000   
1                                 27.520000                         173.00000   
2                                 11.970000                         377.00000   
3                                 -2.490000                         360.00000   
4                                  6.720000                         211.00000   
...                                     ...                               ...   
3313                            2625.514643                       13599.07143   
3314                            2626.338571                       13603.28571   
3315                            2627.162500                       13607.50000   
3316                            2627.986429                       13611.71429   
3317                            2628.810357                       13615.92857   

      Gapingin-between voiced\nintervals(-/min)  \
0                                     58.650000   
1                                     48.260000   
2                                     47.540000   
3                                     13.720000   
4                                     42.900000   
...                                         ...   
3313                               -3221.373571   
3314                               -3222.398571   
3315                               -3223.423571   
3316                               -3224.448571   
3317                               -3225.473571   

      Duration of unvoiced stops (ms)  \
0                           31.380000   
1                           22.380000   
2                           38.120000   
3                           44.880000   
4                           47.120000   
...                               ...   
3313                      3744.913929   
3314                      3746.080000   
3315                      3747.246071   
3316                      3748.412143   
3317                      3749.578214   

      Decay of unvoiced fricatives(promile/min)  \
0                                     -2.101000   
1                                     -1.745000   
2                                      2.657000   
3                                     -0.934000   
4                                     -0.973000   
...                                         ...   
3313                                2446.410393   
3314                                2447.178714   
3315                                2447.947036   
3316                                2448.715357   
3317                                2449.483679   

      Entropy of speech timing (-).1  Acceleration of speech timing (-/min2)  \
0                           1.564000                               -2.820000   
1                           1.569000                                8.200000   
2                           1.550000                                4.710000   
3                           1.539000                               -9.090000   
4                         

In [28]:
X = df.loc[:, 'Age' : 'Latency of\nrespiratory exchange (ms).1'].values
y = df['Status'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Scaling using MinMax
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train.shape
#
Features=df.columns[:-1]
Features

Index(['Age', 'History', 'Tremor', 'Leg agility',
       'Entropy of speech timing (-)', 'Acceleration of speech timing(-/min2)',
       'Duration of pause intervals (ms)',
       'Gapingin-between voiced\nintervals(-/min)',
       'Duration of unvoiced stops (ms)',
       'Decay of unvoiced fricatives(promile/min)',
       'Entropy of speech timing (-).1',
       'Acceleration of speech timing (-/min2)',
       'Duration of unvoiced stops (ms).1',
       'Rate of speech respiration (- /min)',
       'Latency of\nrespiratory exchange (ms).1'],
      dtype='object')

In [53]:
X = df.loc[:, 'Age' : 'Latency of\nrespiratory exchange (ms).1'].values
y = df['Status'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Scaling using MinMax
scaler = MinMaxScaler()

X_train2 = scaler.fit_transform(X_train)
X_train2
X_train

array([[6.70000000e+01, 1.00000000e+00, 1.00000000e+00, ...,
        2.12898786e+03, 3.60846429e+02, 1.17207143e+03],
       [7.40000000e+01, 1.00000000e+00, 1.00000000e+00, ...,
        3.02462143e+02, 6.14292857e+01, 2.79500000e+02],
       [6.50000000e+01, 1.00000000e+00, 1.00000000e+00, ...,
        1.58794393e+03, 2.72154643e+02, 9.07678571e+02],
       ...,
       [6.80000000e+01, 1.00000000e+00, 1.00000000e+00, ...,
        9.66507143e+02, 1.70284286e+02, 6.04000000e+02],
       [6.30000000e+01, 0.00000000e+00, 0.00000000e+00, ...,
        6.17602143e+02, 1.13089286e+02, 4.33500000e+02],
       [5.90000000e+01, 0.00000000e+00, 1.00000000e+00, ...,
        2.47789286e+03, 1.41987680e+02, 5.19683320e+02]])

In [79]:
# User defined function to take patients input and give a diagnosis
def Perkinsons():
  # These are the Features
  cols=Features
  # The main DataFrame
  user_df=pd.DataFrame(columns=cols)
  user_df
  # Creating an empty break
  columns=[]
  # Iterating through evvery input to take in the value of the patients
  for i in cols:
    dp=str(input(i))
    columns.append(dp)
    print(dp)
  # User inputs
  my_df=pd.DataFrame(data=columns,index=cols)
  transposed=my_df.transpose()
  # Concating my inputs to the initial dataframe
  user_df=pd.concat([user_df,transposed],axis=0)
  user_df.dtypes

  # Taking the input for a patient at a time
  user_df

  # Changing datatypes to numeric To enable encoding of categorical features

  to_float=['Age','Entropy of speech timing (-)','Acceleration of speech timing(-/min2)',
        'Duration of pause intervals (ms)',
        'Gapingin-between voiced\nintervals(-/min)',
        'Duration of unvoiced stops (ms)',
        'Decay of unvoiced fricatives(promile/min)',
        'Entropy of speech timing (-).1',
        'Acceleration of speech timing (-/min2)',
        'Duration of unvoiced stops (ms).1',
        'Rate of speech respiration (- /min)',
        'Latency of\nrespiratory exchange (ms).1']
  user_df[to_float]=user_df[to_float].astype(float)
  user_df.dtypes
  # # Picking object types
  # # objects=user_df.select_dtypes('object')
  # # objects
  # Using numpy to encode my inputs
  user_df[['History','Tremor','Leg agility']]=np.where(user_df[['History','Tremor','Leg agility']]=='Yes',1,0)
  user_df
  # Defining my features
  X_feat=user_df.values.reshape(1, -1)
  X_feat
  # # # Predicting the status of patient 0
  scaler = MinMaxScaler()
  scaler.fit(X_train)
  # Transforming the test set
  X_feat = scaler.transform(X_feat)
  X_feat
  # # Using the Scaled features to perform prediction
#   loaded_model=pickle.load(open(filename,'rb'))
#   Diagnosis=loaded_model.predict(X_feat)
#   Diagnosis
  Diagnosis=final_model.predict(X_feat)
  Diagnosis
  # Output
  if Diagnosis ==[0]:
    print(' Congratulations,You dont have Perkinsons')
  else:
    print('Sooooo Sorry: You Garit!!')
  return

In [80]:
Perkinsons()

40
No
No
Yes
1
1
1
1
1
1
1
1
1
1
1
Sooooo Sorry: You Garit!!


In [45]:
X_train

array([[0.6       , 1.        , 1.        , ..., 0.82042645, 0.93045491,
        0.93547252],
       [0.95      , 1.        , 1.        , ..., 0.11210855, 0.14042266,
        0.20244031],
       [0.5       , 1.        , 1.        , ..., 0.61061221, 0.69643567,
        0.71833754],
       ...,
       [0.65      , 1.        , 1.        , ..., 0.36962201, 0.42764389,
        0.46893882],
       [0.4       , 0.        , 0.        , ..., 0.23431832, 0.27673104,
        0.32891418],
       [0.2       , 0.        , 1.        , ..., 0.95573013, 0.3529814 ,
        0.39969299]])

In [81]:
# Model 4 dash

def dash(val1, val2, val3, val4, val5, val6, val7, val8, val9, val10, val11, val12, val13, val14, val15):
    X_new = np.array([val1, val2, val3, val4, val5, val6, val7, val8, val9, val10, val11, val12, val13, val14, val15]).reshape(1, -1)
    #Scale the values
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_new = scaler.transform(X_new)
    
    Diagnosis=final_model.predict(X_new)
    Diagnosis
    # Output
    if Diagnosis < [1]:
        print(' Congratulations,You dont have Perkinsons')
    else:
        print('Sooooo Sorry: You Garit!!')
    return
    

In [82]:
dash(1, 88, 3, 4, 5, 6, 88, 8, 9, 100, 11, 12, 136, 14, 15)


Sooooo Sorry: You Garit!!


In [71]:
df.iloc[1].values

array([ 72.   ,   0.   ,   1.   ,   0.   ,   1.564,  27.52 , 173.   ,
        48.26 ,  22.38 ,  -1.745,   1.569,   8.2  ,  26.88 ,  21.77 ,
       313.   ,   0.   ])

In [44]:
yo = np.array([1, 2, 3])
yo

array([1, 2, 3])